### PR TITLE
run shellcheck

### PR DESCRIPTION
**Pull request by aviau**
unsure about some of these, opening PR as backup

### CODE REVIEW

**Comment by leameow** [comment]
Look good to me! What are you unsure about? the `local var; var=xyz`?

**Comment by leameow** [comment]
I actually look up why shellcheck was enforcing this pattern: https://github.com/koalaman/shellcheck/wiki/SC2155#problematic-code-in-the-case-of-local 

Look sensible to me!

**Review by leameow — APPROVED** [review]

**Comment by aviau** [comment]
I was worried about `"${telepresence_options[@]}"`. I just want to make sure they are still separate args.

**Comment by aviau** [comment]
Yep, everything still works.

**Comment by aviau** [comment]
> Look good to me! What are you unsure about? the local var; var=xyz?

Ill use that syntax instead!

**Pull request merged**
